Cypress
lageIBUSP/notaR pull request #100
Opened 2024-04-09 19:50 UTC by Lobz

Adição de testes de integração cypress

2024-04-09 23:04 UTC, andrechalom requested changes

2024-04-09 23:04 UTC, andrechalom commented on tests/cypress/integration/admin_login.cy.js
> +    cy.contains('Entrar').click();
Sugiro adotar um padrão quanto a usar ; no final de cada linha

2024-04-09 23:04 UTC, andrechalom commented on tests/cypress/integration/example.cy.js
> +describe('Example Test', () => {
Talvez seja melhor remover / renomear

2024-04-09 23:04 UTC, andrechalom commented on tests/cypress/integration/exercicio_create.cy.js
> +describe('Login test', () => {
A descrição está errada

2024-04-09 23:04 UTC, andrechalom commented on tests/cypress/support/routes.json
> +{
Esse arquivo é autogerado? Se sim, é melhor documentar como atualizar

2024-04-10 17:10 UTC, Lobz commented on tests/cypress/support/routes.json
> +{
documentar onde?

2024-04-10 17:15 UTC, Lobz commented on tests/cypress/support/routes.json
> +{
documentei no readme

2024-04-10 20:12 UTC, andrechalom approved these changes

2024-04-10 20:25 UTC, merged