Bulk
lageIBUSP/notaR pull request #103
Opened 2024-04-12 19:16 UTC by Lobz

Bulk adding users now through a csv file with name and email fields

2024-04-19 19:30 UTC, andrechalom requested changes

2024-04-19 19:30 UTC, andrechalom commented on resources/views/exercicio/show.blade.php
> +        <input type="text" id="oi" name="oi" value="oi">
plz remove

2024-04-19 19:30 UTC, andrechalom commented on resources/views/turma/edit.blade.php
> +	    <form action={{URL::to('/turma/'.$turma->id)}} method="POST" enctype="multipart/form-data">
Seria bom ter um link para o arquivo de exemplo

2024-04-19 19:30 UTC, andrechalom commented on app/Rules/CsvRule.php
> +
Por que esse arquivo tem tantas linhas em branco?

2024-04-19 19:30 UTC, andrechalom commented on app/Http/Controllers/TurmaController.php
> +use App\Rules\CsvRule;
A classe App\Rules\Emails ainda é usada em algum lugar? Se não, podemos remover

2024-04-19 22:22 UTC, Lobz commented on resources/views/turma/edit.blade.php
> +	    <form action={{URL::to('/turma/'.$turma->id)}} method="POST" enctype="multipart/form-data">
+ escrever um csv de exemplo

2024-05-15 18:00 UTC, Lobz commented
plz review again

2024-05-15 20:51 UTC, andrechalom commented on storage/app/public/examples/exercicio.yaml
> +name: '101.00 Bem-vindo(a) ao notaR'
👍 👍

2024-05-15 20:52 UTC, andrechalom commented on docker-compose.yml
> +            - './storage/app/public/examples:/examples'
Pq montar esse volume como /examples?

2024-05-15 20:52 UTC, andrechalom approved these changes

2024-05-15 21:14 UTC, merged