Topicos
lageIBUSP/notaR pull request #122
Opened 2024-06-11 18:20 UTC by Lobz

Adding Topicos to organize Exercícios, to close Issue #106

2024-06-28 21:55 UTC, andrechalom commented on app/Http/Controllers/TopicoController.php
> +    $semTopico = Exercicio::whereDoesntHave('topico')->orderBy('name');
Precisa filtrar pelos exercícios publicados aqui tbm

2024-06-28 21:56 UTC, andrechalom commented on app/Http/Controllers/ExercicioController.php
> +    return redirect()->action([TopicoController::class, 'index']);
Dá pra procurar como manter a URL (lembro q tem como fazer um render do TopicoController sem fazer redirect)

2024-06-28 21:58 UTC, andrechalom commented on app/Http/Controllers/TopicoController.php
> +    return redirect()->action([get_class($this), 'index']);
Faz sentido adicionar um anchor?

2024-06-28 22:00 UTC, andrechalom commented on database/factories/TopicoFactory.php
> +<?php
É útil?

2024-06-28 22:01 UTC, andrechalom commented on docker/php/php.ini
> +xdebug.mode = debug,profile
Não pode!!!!!

2024-06-28 22:03 UTC, andrechalom commented on database/factories/TopicoFactory.php
> +<?php
Talvez criar um seeder aqui

2024-06-28 22:06 UTC, andrechalom commented on resources/views/topico/create.blade.php
> +	    <form action="{{URL::to("/topico")}}" method="{{ isset($topico) ? 'put' : 'post'}}">
Aqui tem um isset q n faz sentido se vc está usando blades diferentes de create e edit

2024-06-28 22:06 UTC, andrechalom commented on resources/views/topico/edit.blade.php
> +	    <form action={{URL::to('/topico/'.$topico->id)}} method="POST" enctype="multipart/form-data">
N precisa ser multipart aqui

2024-06-28 22:07 UTC, andrechalom commented on resources/views/exercicio/index.blade.php
>  @section('content')
Esse arquivo ainda existe? Faz sentido?

2024-06-28 22:12 UTC, andrechalom requested changes
Plz review

2024-07-01 22:08 UTC, Lobz commented on app/Http/Controllers/TopicoController.php
> +    return redirect()->action([get_class($this), 'index']);
vou deixar isso pra depois

2024-07-02 15:21 UTC, andrechalom approved these changes

2024-07-02 15:22 UTC, merged